### ISSUE TITLE
As a user I'd like to know about the various scanning projects we have around the world

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/laws-africa.github.io#46]
The idea here is to have a page profiling our "Scan Stations", such as those in Zim, Cape Town, Berlin, Ghana, etc.

At a high level, this is a list of the scan stations and markers on a map. This will highlight our diverse network and raise the profile of the teams who do the hard work to do the scanning.

## Proposal

For each station, we should have:

1. a name, eg "Scan Station Cape Town"
2. map coordinates
3. the location name, eg "Cape Town, South Africa"
4. a photo
5. name of the staff
6. launch date

On the page, we can have:

1. a brief overview of the Scan Station project (ie. what they are and what they do).
2. a Leaflet.js map with the map markers for each station
3. a list of the scan stations, with a Bootstrap card for each station. Perhaps two columns of cards?

I suggest we store the data in the metadata part of the github pages page, which we can edit through siteleaf, something like:

```
title: foo
...
stations:
- name: Scan Station Cape Town
  location: Cape Town, South Africa
  staff: X, Y and Z
  launch_date: 2019-01-01
```
